---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r}
setwd("C:/git/RepData_PeerAssessment1")
```
## Loading and preprocessing the data
```{r}
library(dplyr)

activity <- read.csv("activity.csv")
activity[is.na(activity)] <- 0
```

## What is mean total number of steps taken per day?
```{r}
activity_sum <- activity %>%
  group_by(date) %>%
    summarise(count = sum(steps), mean_steps= mean(steps), median_steps=median(steps))
```

###Histogram here
```{r}
library(ggplot2)
bar <- ggplot(activity_sum, aes(x=date, y=count)) + geom_bar(stat="identity") 
bar
```

##Mean and median total number of steps taken per day

```{r}
summary <- activity_sum %>% 
                  select(date, mean_steps, median_steps)

summary
```

##Average daily activity pattern
```{r}
activity_interval <- activity %>%
  group_by(interval) %>%
    summarise(mean_steps= mean(steps))

max <- max(activity_interval$mean_steps) # Find a dplyr way to do this.
max_interval <- activity_interval %>% filter(mean_steps == max) %>% select(interval)

ggplot(activity_interval,aes(interval, mean_steps)) +
  geom_line() 
#+ geom_text(data=activity_interval[max_interval, max], label="note" , vjust=1, colour="red")


```

######5-minute interval that has the average maximum number of steps is `r max_interval`